'\" t
.\"     Title: vasm
.\"    Author: VOLT Foundation
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2024-10-22
.\"    Manual: VASM
.\"    Source: VASM
.\"  Language: English
.\"
.TH "VASM" "1" "2024-10-22" "VASM" "VASM"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "VASM"
vasm \- A compiler for the OpenLUD, NexFUSE, SolarisVM, and JADE VMs.
.SH "SYNOPSIS"
.sp
vasm [FILE ...] [OPTIONS ...]
.SH "DESCRIPTION"
.sp
A standard compiler for LR Assembly, a weakly typed assembler language designed
to be compatible with multiple VM environments.
.SH "OPTIONS"
.sp
\-h, \-\-help
.RS 4
Shows the help menu. Note: this is a work in progress and currently does not show anything on Windows devices because of execve being used to run \f(CRman\fP. As the frontend begins to become stabilized this will change.
.RE
.sp
\-\-no\-stylist
.RS 4
Disables running stylist when compiling a program. This disables any compile\-time checks and also conflicts with the \f(CR\-\-enforce\-stylist\fP flag.
.RE
.sp
\-\-strict | \-\-enforce\-stylist
.RS 4
Quits compilation early if stylist reports any style or potential UB issues. Useful for writing strictly typed LR assembly.
.RE
.sp
\-ln, \-\-allow\-large\-numbers
.RS 4
Allows for large numbers to be in the program. (disabling lex\-time checks for large numbers)
It is recommended to keep this option ON as it prevents UB [1] from occuring within the program.
.RE
.sp
\-le
.RS 4
Specifies the \f(CRendian\fP flag as \fBbig\fP in the compiler\(cqs options. The endian flag controls the endianness of the binary generation.
.RE
.sp
\-be
.RS 4
Specifies the \f(CRendian\fP flag as \fBlittle\fP in the compiler\(cqs options. The endian flag controls the endianness of the binary generation.
.RE
.sp
\-f, \-\-format FORMAT
.RS 4
Specifies the output format for the binary. This output format will be the basis for any operations moving forward. This format flag is converted from a string to an enum that contains the format\(cqs information. The format is used for
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Lexer number sizes
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Vendor sizes
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Vendor name
.RE
.RE
.sp
\-o, \-\-output FILE
.RS 4
Specifies the output location of the binary. This location \fBmust\fP be a file, it can not be a directory.
.RE
.sp
\-O[N]
.RS 4
Sets the optimization level to \fBN\fP. For some architectures this will have an effect on what context is chosen and passed to the generator, and others it may not.
.RE
.SH "VENDORS"
.sp
A "vendor" is defined as information to help generate binaries based on documented instructions sets. Instead of mapping each instruction to a number, vasm supports generation of binaries through hand\-implemented functions which are children of instructions. Using the VASM zig API, the OpenLUD vendor is created using the following method:
.sp
.if n .RS 4
.nf
.fam C
pub fn vendor(vend: *codegen.Vendor(i8)) !void {
    vend.nul_after_sequence = true;
    vend.nul_byte = 0;

    try vend.createAndImplementInstruction(i8, "echo", &echoInstruction);
    try vend.createAndImplementInstruction(i8, "mov", &moveInstruction);
    try vend.createAndImplementInstruction(i8, "each", &eachInstruction);
    try vend.createAndImplementInstruction(i8, "init", &initInstruction);
    // ...
}
.fam
.fi
.if n .RE
.sp
The above example uses \f(CRcreateAndImplementInstruction\fP to implement a couple instructions that are specific to the OpenLUD format. These are optional as they are a part of the compilation process and not the language itself. Vendors are just a separate implementation that defines a streamlined process of compiling and verifying binaries.
.sp
Vendors then take input source and turn it into a \fBPROCEDURE MAP\fP that can then be operated on separately. Procedure maps are key\-value pairs that represent the procedure hierarchy of a program. Procedures can be tagged by size (example a \fB5\-byte procedure\fP) and in that stage is where peephole optimizations can take place. The peephole optimizer (defined in \fIpeephole.zig\fP) is not aware of the original source code and only aware of the generated binary, however, using information given to the optimizer prior, is able to free up and remove procedures that go unused.
.sp
In hindsight, this doesn\(cqt have much benefit aside from memory consumption when procedure folding is enabled, however, using \fINexFUSE\-like Procedures\fP (where each procedure label is engraved in the resulting binary) yields higher results.
.SH "INFORMATION"
.sp
This document\(cqs version is 1.0.0.
.SH "NOTES"
.IP [1]
UB stands for "Undefined Behavior". Essentially when anything uncontrollable or unpredictable happens within the program that is not going to or not currently planned to be fixed. A way for developers to cut off specific parts of their program that are too non\-conforming to be manageable.
.SH "AUTHOR"
.sp
VOLT Foundation